# Generated by Django 4.0.1 on 2022-02-28 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capture', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='question',
            new_name='uestion',
        ),
    ]
